import type {ManagedSource, Plugin} from 'onecmd';
import {isStringArray} from './util/is-string-array';
import {serializeLines} from './util/serialize-lines';

export const git = (): Plugin => ({
  sources: [
    {
      type: 'managed',
      path: '.gitignore',
      versionable: true,
      is: isStringArray,

      create: (otherSources) =>
        Object.entries(otherSources).reduce(
          (paths, [path, {versionable}]) =>
            versionable ? paths : [...paths, path],
          ['# This file is generated by @onecmd/standard-plugins.']
        ),

      serialize: serializeLines,
    } as ManagedSource<readonly string[]>,
  ],
});
