import type {Plugin} from 'onecmd';
import {serializeText} from './util/serialize-text';

export const git = (): Plugin => ({
  sources: [
    {
      type: 'string',
      path: '.gitignore',
      versioned: true,

      generate: (otherSources) =>
        Object.entries(otherSources)
          .reduce(
            (paths, [path, {versioned}]) =>
              versioned ? paths : [...paths, path],
            ['# This file is generated by onecmd.']
          )
          .join('\n'),

      serialize: serializeText,
    },
  ],
});
