/* eslint-disable @typescript-eslint/require-await */

import type {Plugin} from 'onecmd';

export const git = (): Plugin => ({
  sources: [
    {
      type: 'text',
      path: '.gitignore',
      versioned: true,

      async generate(otherSources) {
        return Object.entries(otherSources).reduce(
          (paths, [path, {versioned}]) =>
            versioned ? paths : [...paths, path],
          ['# This file is generated by onecmd.']
        );
      },
    },
  ],
});
